name: Npm and Github package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

 
          
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/

 

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Publish to NPM
      
        run: |
          if [ "$GIT_REF" = "refs/heads/master" ] ; then
            npm version patch --no-git-tag-version
            npm run build
            echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
            npm publish -q
          fi
        env:
          GIT_REF: ${{ github.ref }}
          NPM_AUTH_TOKEN: ${{secrets.AUTH_NPM}}
 
